# Generated by Django 4.2.1 on 2023-05-12 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0005_remove_patient_personalinformations'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnthropometricEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('PhysicalActivityLevel', models.FloatField(blank=True)),
                ('currentWeight', models.FloatField(blank=True)),
                ('Circumferenceabdominal', models.FloatField(blank=True)),
                ('Circumferencewaist', models.FloatField(blank=True)),
                ('Circumferencearm', models.FloatField(blank=True)),
                ('Circumferencecalf', models.FloatField(blank=True)),
                ('Circumferencehip', models.FloatField(blank=True)),
                ('SkinfoldBiceps', models.FloatField(blank=True)),
                ('SkinfoldTriceps', models.FloatField(blank=True)),
                ('SkinfoldSubscapular', models.FloatField(blank=True)),
                ('SkinfoldMediumAxillary', models.FloatField(blank=True)),
                ('SkinfoldSuprailiac', models.FloatField(blank=True)),
                ('SkinfoldSupraspinal', models.FloatField(blank=True)),
                ('SkinfoldAbdominal', models.FloatField(blank=True)),
                ('SkinfoldThigh', models.FloatField(blank=True)),
                ('SkinfoldCalf', models.FloatField(blank=True)),
                ('SkinfoldBreastplate', models.FloatField(blank=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
