# Generated by Django 4.2.1 on 2023-05-12 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0005_remove_patient_personalinformations'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlterationDigestiveSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alteration', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Condiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condiction', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(blank=True, default='', max_length=50)),
                ('food', models.CharField(blank=True, default='', max_length=50)),
                ('quantity', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug', models.CharField(blank=True, default='', max_length=50)),
                ('dose', models.CharField(blank=True, default='', max_length=50)),
                ('schedule', models.TimeField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AllergyOrIntolerance', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wakeUp', models.TimeField(blank=True, default='')),
                ('sleeps', models.TimeField(blank=True, default='')),
                ('physicalActivity', models.TimeField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weightChanges', models.IntegerField(blank=True)),
                ('obsPhysicalExam', models.TextField(blank=True, default='', max_length=50)),
                ('obsDisgestiveSystem', models.TextField(blank=True, default='', max_length=50)),
                ('intestinalChanges', models.CharField(blank=True, default='', max_length=50)),
                ('obsIntestinalChanges', models.TextField(blank=True, default='')),
                ('waterConsumption', models.CharField(blank=True, default='', max_length=50)),
                ('alcoholicBeverage', models.CharField(blank=True, default='', max_length=50)),
                ('smoking', models.CharField(blank=True, default='', max_length=50)),
                ('physicalActivityDescription', models.CharField(blank=True, default='', max_length=100)),
                ('foodPreferences', models.TextField(blank=True, default='')),
                ('foodAversions', models.TextField(blank=True, default='')),
                ('inappetence', models.TextField(blank=True, default='')),
                ('hyperphagia', models.TextField(blank=True, default='')),
                ('alterationDisgestiveSystem', models.ManyToManyField(to='medicalInformations.alterationdigestivesystem')),
                ('dietEvaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalInformations.diet')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('physicalExam', models.ManyToManyField(to='medicalInformations.condiction')),
                ('restrictions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalInformations.restriction')),
                ('schedules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalInformations.schedules')),
                ('useOfMedicines', models.ManyToManyField(to='medicalInformations.medicationuse')),
            ],
        ),
    ]
