# Generated by Django 4.2.1 on 2023-05-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patient_phone_patient_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
    ]
