# Generated by Django 4.2.1 on 2023-05-12 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personalInformations', '0001_initial'),
        ('patients', '0003_rename_phone_number_patient_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='personalInformations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personalInformations.personalinformation'),
        ),
    ]
